
import 'package:mentegoz_technologies/modelclass.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
Future<List<Autogenerated>> fetchAlbum( ) async {
  final prefs = await SharedPreferences.getInstance();
// ignore: unused_local_variable
String ?Firebase_Id=prefs.getString('Firebase_Id');
print(Firebase_Id);
print('++++++++++++++++++++++');
    // final firebaseIdProvider =
    //     Provider.of<FirebaseIdProvider>(context, listen: false);
    final response = await http.post(
      Uri.parse('https://antes.meduco.in/api/get_services'),
      body: {
        'firebase.id':Firebase_Id,
      },
    );
print(response.statusCode);

    if (response.statusCode == 200) {
      // If the server did return a 200 OK response,
      // then parse the JSON.
      // return Datum.fromJson(jsonDecode(response.body));
      print("Got Response!");

      var data = GeneratedFromJson(response.body);
      print(data);
      return data;
    } else {
      // If the server did not return a 200 OK response,
      // then throw an exception.
      throw Exception('Failed to load album');
    }
  }